### PR TITLE
Append missing instruction symbolic expressions when AST_OPTIMIZATIONS are enabled

### LINKED ISSUE #1002: AST_OPTIMIZATIONS and newSymbolicExpression
There something wrong with `AST_OPTIMIZATIONS` and `SymbolicEngine::newSymbolicExpression`. In a specific case, caling `newSymbolicExpression` results in [two calls](https://github.com/JonathanSalwan/Triton/blob/25b4c04d68924b516b3443faad47a76d5c9af221/src/libtriton/engines/symbolic/symbolicEngine.cpp#L363) of this function which do not link the first symbolic expression created to the current instruction.

PoC below:

```python
from triton import TritonContext, Instruction, ARCH, MODE

ctx = TritonContext(ARCH.X86_64)
ctx.setMode(MODE.AST_OPTIMIZATIONS, True)

inst = Instruction(b"\x29\xca")
ctx.processing(inst)

exprs = ctx.getSymbolicExpressions()
for i in sorted(exprs):
    print(i, exprs[i])


print("="*10+"\n")
for e in inst.getSymbolicExpressions():
    print(e)
```

Symbolic expressions from the TritonContext:

```
0 (define-fun ref!0 () (_ BitVec 32) (_ bv0 32)) ; Extended part - SUB operation - 0x0: sub edx, ecx
1 (define-fun ref!1 () (_ BitVec 64) ((_ zero_extend 32) ref!0)) ; SUB operation - 0x0: sub edx, ecx
2 (define-fun ref!2 () (_ BitVec 1) (ite (= (_ bv16 32) (_ bv0 32)) (_ bv1 1) (_ bv0 1))) ; Adjust flag - 0x0: sub edx, ecx
3 (define-fun ref!3 () (_ BitVec 1) ((_ extract 31 31) (_ bv0 32))) ; Carry flag - 0x0: sub edx, ecx
4 (define-fun ref!4 () (_ BitVec 1) ((_ extract 31 31) (_ bv0 32))) ; Overflow flag - 0x0: sub edx, ecx
5 (define-fun ref!5 () (_ BitVec 1) (_ bv1 1)) ; Parity flag - 0x0: sub edx, ecx
6 (define-fun ref!6 () (_ BitVec 1) ((_ extract 31 31) ref!1)) ; Sign flag - 0x0: sub edx, ecx
7 (define-fun ref!7 () (_ BitVec 1) (ite (= ref!0 (_ bv0 32)) (_ bv1 1) (_ bv0 1))) ; Zero flag - 0x0: sub edx, ecx
8 (define-fun ref!8 () (_ BitVec 64) (_ bv2 64)) ; Program Counter - 0x0: sub edx, ecx
```

Symbolic expressions from the instruction:

```
(define-fun ref!1 () (_ BitVec 64) ((_ zero_extend 32) ref!0)) ; SUB operation - 0x0: sub edx, ecx
(define-fun ref!2 () (_ BitVec 1) (ite (= (_ bv16 32) (_ bv0 32)) (_ bv1 1) (_ bv0 1))) ; Adjust flag - 0x0: sub edx, ecx
(define-fun ref!3 () (_ BitVec 1) ((_ extract 31 31) (_ bv0 32))) ; Carry flag - 0x0: sub edx, ecx
(define-fun ref!4 () (_ BitVec 1) ((_ extract 31 31) (_ bv0 32))) ; Overflow flag - 0x0: sub edx, ecx
(define-fun ref!5 () (_ BitVec 1) (_ bv1 1)) ; Parity flag - 0x0: sub edx, ecx
(define-fun ref!6 () (_ BitVec 1) ((_ extract 31 31) ref!1)) ; Sign flag - 0x0: sub edx, ecx
(define-fun ref!7 () (_ BitVec 1) (ite (= ref!0 (_ bv0 32)) (_ bv1 1) (_ bv0 1))) ; Zero flag - 0x0: sub edx, ecx
(define-fun ref!8 () (_ BitVec 64) (_ bv2 64)) ; Program Counter - 0x0: sub edx, ecx
```

The symbolic expression `0` is missing from the instruction's symbolic expressions set.

### PR DESCRIPTION
**Pull request by SweetVishnya**
Closes #1002

### CODE REVIEW

File: src/libtriton/engines/symbolic/symbolicEngine.cpp [hunk 1]
```diff
@@ -963,6 +963,7 @@ namespace triton {
         SharedSymbolicExpression se         = nullptr;
         triton::uint64 address              = mem.getAddress();
         triton::uint32 writeSize            = mem.getSize();
+        auto id                             = this->uniqueSymExprId;
```
Comment (JonathanSalwan) [inline src/libtriton/engines/symbolic/symbolicEngine.cpp:966]: Can we avoid as much as possible the `auto` keyword? I think it's more readable for ppl who want to take a look at Triton internals than reading the prototype of what `uniqueSymExprId` is. For those kind of declaration I used to use the type `triton::usize`.

However, I can accept the `auto` keyword when lines are too long without it or in loops like: `for (auto& e : l)`. Semantics files are the only exception.

File: src/libtriton/engines/symbolic/symbolicEngine.cpp [hunk 2]
```diff
@@ -1020,7 +1023,11 @@ namespace triton {
         se = this->newSymbolicExpression(tmp, MEMORY_EXPRESSION, "Temporary concatenation reference - " + s.str());
         se->setOriginMemory(triton::arch::MemoryAccess(address, mem.getSize()));
 
-        return inst.addSymbolicExpression(se);
+        /* See #1002: There may be multiple new symbolic expressions when AST_OPTIMIZATIONS are on */
```
Comment (JonathanSalwan) [inline src/libtriton/engines/symbolic/symbolicEngine.cpp:1026]: The label `ret:` here

File: src/libtriton/engines/symbolic/symbolicEngine.cpp [hunk 3]
```diff
@@ -1007,6 +1006,10 @@ namespace triton {
         if (ret.size() == 1) {
           /* Synchronize the concrete state */
           this->architecture->setConcreteMemoryValue(mem, tmp->evaluate());
+          /* See #1002: There may be multiple new symbolic expressions when AST_OPTIMIZATIONS are on */
+          for (auto i = id; i != this->uniqueSymExprId; ++i) {
+            inst.addSymbolicExpression(this->getSymbolicExpression(i));
+          }
```
Comment (JonathanSalwan) [inline src/libtriton/engines/symbolic/symbolicEngine.cpp:1012]: I'm not really ok to add `goto` everywhere but I think we can do an exception here to avoid redundant code. So, i think we can replace those 4 lines above with a `goto ret;`. See the label below.

File: src/libtriton/engines/symbolic/symbolicEngine.cpp [hunk 4]
```diff
@@ -1094,20 +1101,30 @@ namespace triton {
 
         std::stringstream s;
         s << comment << (comment.empty() ? "" : " - ") << inst;
+        auto id = this->uniqueSymExprId;
```
Comment (JonathanSalwan) [inline src/libtriton/engines/symbolic/symbolicEngine.cpp:1104]: `triton::usize`

File: src/libtriton/engines/symbolic/symbolicEngine.cpp [hunk 5]
```diff
@@ -1094,20 +1101,30 @@ namespace triton {
...
+        }
+        return inst.symbolicExpressions.back();
       }
 
 
       /* Returns the new symbolic volatile expression */
       const SharedSymbolicExpression& SymbolicEngine::createSymbolicVolatileExpression(triton::arch::Instruction& inst, const triton::ast::SharedAbstractNode& node, const std::string& comment) {
         std::stringstream s;
         s << comment << (comment.empty() ? "" : " - ") << inst;
+        auto id = this->uniqueSymExprId;
```
Comment (JonathanSalwan) [inline src/libtriton/engines/symbolic/symbolicEngine.cpp:1121]: `triton::usize`

**Comment by JonathanSalwan** [comment]
Nice PR, thanks!

File: src/libtriton/engines/symbolic/symbolicEngine.cpp (hunk 3 above)
Comment (SweetVishnya) [reply src/libtriton/engines/symbolic/symbolicEngine.cpp:1012]: I can write a private function ;)

File: src/libtriton/engines/symbolic/symbolicEngine.cpp (hunk 1 above)
Comment (SweetVishnya) [reply src/libtriton/engines/symbolic/symbolicEngine.cpp:966]: Ok, I'll fix it and try to remember this for future.

**Comment by SweetVishnya** [comment]
Resolved review issues.

**Comment by SweetVishnya** [comment]
Still need to fix some CI(

**Comment by SweetVishnya** [comment]
Pushed commit with an attempt to fix CI.

**Comment by SweetVishnya** [comment]
CI is green)

**Comment by JonathanSalwan** [comment]
Thanks!
